### ISSUE TITLE
Issues with PyQt5

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/slicer-manual-annotation#47]
**Describe the bug**

When starting Slicer3D, upon loading of the SlicerCART (version 12b1f64cea242eeebdaf88d20f2e666275e3ab8a), PyQt5 cannot be imported:

```console
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.9/imp.py", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/julien/code/slicer-manual-annotation/SlicerCART/src/SlicerCART.py", line 73, in <module>
    from PyQt5 import QtCore
ImportError: cannot import name 'QtCore' from 'PyQt5' (unknown location)
[Qt] loadSourceAsModule - Failed to load file "/Users/julien/code/slicer-manual-annotation/SlicerCART/src/SlicerCART.py"  as module "SlicerCART" !
[Qt] Fail to instantiate module  "SlicerCART"
[Qt] The following modules failed to be instantiated:
[Qt]    SlicerCART
[Qt] Populating font family aliases took 184 ms. Replace uses of missing font family ".AppleSystemUIFont" with one that exists to avoid this cost. 
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ImportError: cannot import name 'QtCore' from 'PyQt5' (unknown location)
```

I then manually reinstalled PyQt5 from the Slicer's python console:
```
slicer.util.pip_install("PyQt5")
```

It stated that the package was already installed, and when I tried to import it again, Slicer crashed.

Upon restarting, the console spit out another message about two versions of PyQt5 being installed:
```console
[FD] objc[4644]: Class QMacAutoReleasePoolTracker is implemented in both /Applications/Slicer.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore (0x10e1429e8) and /Applications/Slicer.app/Contents/lib/Python/lib/python3.9/site-packages/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore (0x1674c6948). One of the two will be used. Which one is undefined.
[FD] objc[4644]: Class QT_ROOT_LEVEL_POOL__THESE_OBJECTS_WILL_BE_RELEASED_WHEN_QAPP_GOES_OUT_OF_SCOPE is implemented in both /Applications/Slicer.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore (0x10e142a60) and /Applications/Slicer.app/Contents/lib/Python/lib/python3.9/site-packages/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore (0x1674c69c0). One of the two will be used. Which one is undefined.
[FD] objc[4644]: Class KeyValueObserver is implemented in both /Applications/Slicer.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore (0x10e142a88) and /Applications/Slicer.app/Contents/lib/Python/lib/python3.9/site-packages/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore (0x1674c69e8). One of the two will be used. Which one is undefined.
[FD] objc[4644]: Class RunLoopModeTracker is implemented in both /Applications/Slicer.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore (0x10e142ad8) and /Applications/Slicer.app/Contents/lib/Python/lib/python3.9/site-packages/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore (0x1674c6a38). One of the two will be used. Which one is undefined.
[Qt] Populating font family aliases took 106 ms. Replace uses of missing font family ".AppleSystemUIFont" with one that exists to avoid this cost. 
Traceback (most recent call last):
  File "<console>", line 1, in <module>
```

Some questions:
- Does Slicer already come with PyQt5 and if so should we avoid re-installing it?
- Before pip-installing it, QtCore could not be imported (using `from PyQt5 import QtCore`). Is this because Slicer's native QtCore should be imported in another way?
- Is this issue what motivated @laurentletg to get rid of PyQt5 import in https://github.com/neuropoly/slicer-manual-annotation/pull/41?

Relevant links:
- https://discourse.slicer.org/t/osx-slicer-qt5-packaging-error/1468
- https://discourse.slicer.org/t/slicer-packaging-qt5-libraries-link/3583
- https://discourse.slicer.org/t/how-to-convert-pyqt-gui-interface-running-in-python-into-module-in-3d-slicer/36366
- https://discourse.slicer.org/t/how-to-access-qtcore-constants-in-python/13137
- https://discourse.slicer.org/t/can-you-use-slicer-modules-within-another-pyqt-project/21878

**Comment by jcohenadad** [comment]
One possible solution is to get rid of `PyQt5` and use `PythonQt` instead. `PythonQt` is native to Slicer and `qtcore` functions can be accessed directly via `qt.`. See https://discourse.slicer.org/t/how-to-access-qtcore-constants-in-python/13137

Is this what you had in mind @laurentletg ? If so I can work on it.
